
clc; clear; close all;
filename = '109samples.csv';
data = readtable(filename);
raw_time = data{:,1}; 
raw_time = erase(raw_time, {'"', ''''}); 
time_div = split(raw_time, {':', '.'}); 
min = str2double(time_div(:,1));
sec = str2double(time_div(:,2));
ms = str2double(time_div(:,3));
idex = ~isnan(min) & ~isnan(sec) & ~isnan(ms);
time = (min(idex) * 60) + sec(idex) + (ms(idex) / 1000);
ecg_data = data{idex,2}; 
dt = diff(time);
fs = 1 / mean(dt); 
L = length(ecg_data);
f = fs * (0:(L/2)) / L;
Y = fft(ecg_data);
P2 = abs(Y/L);
P1 = P2(1:L/2+1);
P1(2:end-1) = 2 * P1(2:end-1);
figure;
subplot(3,1,1);
plot(time, ecg_data);
title('ECG Signal'); xlabel('Time (s)'); ylabel('Amplitude'); grid on;
subplot(3,1,2);
plot(f, P1);
title('FFT Before Notch Filter'); xlabel('Frequency (Hz)'); ylabel('|P1(f)|'); grid on;
f0 = 50; 
Q = 35; 
wo = f0 / (fs/2);  
bw = wo / Q;
[b, a] = iirnotch(wo, bw);
filt = filtfilt(b, a, ecg_data);
y_filt = fft(filt);
p2_filt = abs(y_filt/L);
p1_filt = p2_filt(1:L/2+1);
p1_filt(2:end-1) = 2 * p1_filt(2:end-1);
subplot(3,1,3);
plot(f, p1_filt);
title('FFT After Notch Filter'); xlabel('Frequency (Hz)'); ylabel('|P1(f)|'); grid on;
